[package]
name = "storage_derive"
version = "0.1.0"
authors = ["Nattapong Sirilappanich <s.nattapong@gmail.com>"]
edition = "2018"
license = "BSD-4-Clause"

[lib]
proc-macro = true

[dependencies]
common = { path = "../../common" }
proc-macro2 = "0.4"
quote = "0.6"
syn = "0.15"