[package]
name = "tensor"
version = "0.1.0"
authors = ["Nattapong Sirilappanich <s.nattapong@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
common = { path = "../common" }
storage = { path = "../storage" }
tensor_derive = { path = "tensor_derive" }

[build-dependencies]